"""add_odds_side

Revision ID: 69954a2a6ca5
Revises: f55f5b444210
Create Date: 2026-01-21 07:09:56.612514

"""

from alembic import op
import sqlalchemy as sa



revision = '69954a2a6ca5'
down_revision = 'f55f5b444210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'odds_new',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('market_id', sa.String(length=36), nullable=False),
        sa.Column('bookmaker_id', sa.String(length=36), nullable=False),
        sa.Column('outcome', sa.String(length=50), nullable=False),
        sa.Column('side', sa.String(length=10), server_default='back', nullable=False),
        sa.Column('price_decimal', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column('pulled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id']),
        sa.ForeignKeyConstraint(['market_id'], ['markets.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'market_id',
            'bookmaker_id',
            'outcome',
            'side',
            'pulled_at',
            name='uq_odds_market_bookmaker_outcome_side_pulled_at',
        ),
    )
    op.execute(
        "INSERT INTO odds_new (id, market_id, bookmaker_id, outcome, side, price_decimal, pulled_at, source) "
        "SELECT id, market_id, bookmaker_id, outcome, 'back', price_decimal, pulled_at, source FROM odds"
    )
    op.drop_table('odds')
    op.rename_table('odds_new', 'odds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'odds_old',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('market_id', sa.String(length=36), nullable=False),
        sa.Column('bookmaker_id', sa.String(length=36), nullable=False),
        sa.Column('outcome', sa.String(length=50), nullable=False),
        sa.Column('price_decimal', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column('pulled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id']),
        sa.ForeignKeyConstraint(['market_id'], ['markets.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'market_id',
            'bookmaker_id',
            'outcome',
            'pulled_at',
            name='uq_odds_market_bookmaker_outcome_pulled_at',
        ),
    )
    op.execute(
        "INSERT INTO odds_old (id, market_id, bookmaker_id, outcome, price_decimal, pulled_at, source) "
        "SELECT id, market_id, bookmaker_id, outcome, price_decimal, pulled_at, source FROM odds"
    )
    op.drop_table('odds')
    op.rename_table('odds_old', 'odds')
    # ### end Alembic commands ###
